import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "API"))

import mdeasm_cli  # noqa: E402


def test_build_completion_index_includes_nested_subcommands():
    parser = mdeasm_cli.build_parser()
    index = mdeasm_cli._build_completion_index(parser)

    assert "" in index
    assert "tasks" in index
    assert "workspaces" in index
    assert "doctor" in index
    assert "list" in index["workspaces"]["subcommands"]
    assert "delete" in index["workspaces"]["subcommands"]
    assert "fetch" in index["tasks"]["subcommands"]
    assert "--probe" in index["doctor"]["options"]


def test_cli_completions_bash_stdout(capsys):
    rc = mdeasm_cli.main(["completions", "bash"])
    assert rc == 0

    out = capsys.readouterr().out
    assert "# Generated by `mdeasm completions bash`" in out
    assert "_mdeasm_complete()" in out
    assert "complete -o default -F _mdeasm_complete mdeasm" in out
    assert "workspaces" in out
    assert "assets" in out


def test_cli_completions_zsh_stdout(capsys):
    rc = mdeasm_cli.main(["completions", "zsh"])
    assert rc == 0

    out = capsys.readouterr().out
    assert "# Generated by `mdeasm completions zsh`" in out
    assert "#compdef mdeasm" in out
    assert "bashcompinit" in out
    assert "complete -o default -F _mdeasm_complete mdeasm" in out


def test_cli_completions_writes_file(tmp_path, capsys):
    out_path = tmp_path / "mdeasm-completion.bash"
    rc = mdeasm_cli.main(["completions", "bash", "--out", str(out_path)])
    assert rc == 0

    emitted = capsys.readouterr().out
    assert emitted == ""
    data = out_path.read_text(encoding="utf-8")
    assert "_MDEASM_SUBCOMMANDS" in data
    assert "complete -o default -F _mdeasm_complete mdeasm" in data
